feat(ingestion): record the latest sent_at for each Team
This is a first step towards being able to notify users when there are
events in-flight that may not have hit the ClickHouse db yet. This
information will be used to determine if we should show a "loading"
indicator in the onboarding UI.

chore: add ingestion warnings for when sent_at is in the future

chore: move team_id, token, sent_at to headers

chore: rewrite test_migration_0273 to handle not use atomic

I was having some issues with the existing setup, the tests started
failing with:

```
django.db.utils.OperationalError: cannot ALTER TABLE "posthog_team" because it has pending trigger events
```

chore: rewrite test_migration_0273 to handle not use atomic

I was having some issues with the existing setup, the tests started
failing with:

```
django.db.utils.OperationalError: cannot ALTER TABLE "posthog_team" because it has pending trigger events
```

chore: remove ingestion warnings

chore: explicitly set the capture date, dont use sent_at

wip

wip

add UPDATE_LATEST_EVENT_CAPTURED_AT